### PR TITLE
Simplify Makefile

### PR DESCRIPTION
**Pull request by rekado**
This patch set simplifies the Makefile.

This makes it much easier for package maintainers to ignore the bundled version of Samtools and Boost, and to build RSEM against system libraries / include headers.  A packager would only have to provide a different value for `CFLAGS` with the appropriate include path and library path.

(I'm packaging RSEM for GNU Guix and I would like to avoid the bundled Boost includes and the bundled version of Samtools.)

### CODE REVIEW

**Comment by rekado** [comment]
I should note that there is little functional difference after my changes.  The biggest functional change is probably that headers are no longer explicitly listed as prerequisites.  As building all rsem tools from scratch only takes a few seconds this is a very small price to pay for enabling optional building against system libraries, in my opinion.

**Comment by mr-c** [comment]
This is great. I'm also packaging rsem for Debian. I've had to patch the Makefile to make use of CPPFLAGS, LDFLAGS, CXXFLAGS, and CFLAGS.

@rekado do you want to add those in or should I make a pull request against your branch?

**Comment by mr-c** [comment]
@rekado a PR with the changes I made for Debian is at https://github.com/deweylab/RSEM/pull/22

**Comment by bli25wisc** [comment]
Hi @rekado , 

Sorry for my late reply and thanks a lot for your effort! Since the RSEM updated several times since your post, I cannot simply merge your request. However, I rewrote RSEM's Makefile according to your and @mr-c 's suggestions.

**Comment by rekado** [comment]
It still takes a lot of patching to make sure that an external samtools and an external htslib (which does not have to be relative to the location of samtools) can be used.  I'm adapting the GNU Guix package for rsem now.

**Comment by bli25wisc** [comment]
Hi rekado,

I agree. However, I do not encourage you to allow RSEM use external samtools/htslib because the included SAMtools is slightly modified for RSEM's purpose. For example, I have modified bam_sort.c, which allows the two mates of a read be adjacent when we run 'samtools sort -n'. If you use an external samtools, 'samtools sort -n' will put all first mates together and then all second mates. This will result a crash on RSEM. John Marshall from SAMtools dev community told me they may consider fix it. But until then, RSEM should only its own local version of SAMtools.

Hope it helps,
Bo

**Pull request closed without merging**
